vich_uploader:
    db_driver: orm

    metadata:
        type: attribute
        file_cache:
            dir: '%kernel.build_dir%/vich_uploader'

    mappings:
        user_photo:
            uri_prefix: /images/
            upload_destination: '%kernel.project_dir%/public/images/'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
